(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
window.addEventListener("load",()=>document.body.classList.add("page-loaded"));
const toggle=$(".menu-toggle"),nav=$(".nav");if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",open)});$$(".nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")))}
const page=document.body.dataset.page;$$("[data-nav]").forEach(a=>{if(a.dataset.nav===page)a.classList.add("active")});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach((el,i)=>{el.style.transitionDelay=Math.min(i*35,280)+"ms";observer.observe(el)});
const progress=$(".scroll-progress"),top=$(".back-top");const scrollUI=()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?scrollY/h*100:0)+"%";top.style.display=scrollY>600?"grid":"none"};addEventListener("scroll",scrollUI,{passive:true});scrollUI();if(top)top.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
$$("[data-count]").forEach(el=>{const target=+el.dataset.count;const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){let n=0;const step=Math.max(1,Math.ceil(target/28));const t=setInterval(()=>{n=Math.min(target,n+step);el.textContent=n;if(n===target)clearInterval(t)},30);o.disconnect()}}),{threshold:.8});o.observe(el)});
$$(".tilt-card").forEach(card=>{card.addEventListener("pointermove",e=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform="perspective(900px) rotateX("+(-y*4)+"deg) rotateY("+(x*5)+"deg) translateY(-3px)"});card.addEventListener("pointerleave",()=>card.style.transform="")});
$$(".magnetic").forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect();el.style.transform="translate("+(e.clientX-r.left-r.width/2)*.08+"px,"+(e.clientY-r.top-r.height/2)*.08+"px)"});el.addEventListener("pointerleave",()=>el.style.transform="")});
const filters=$$(".filter"),cards=$$(".project-card"),search=$("#project-search"),empty=$("#empty-state");function filterProjects(){const active=$(".filter.active")?.dataset.filter||"all",q=(search?.value||"").toLowerCase().trim();let count=0;cards.forEach(c=>{const ok=(active==="all"||c.dataset.category===active)&&(!q||c.dataset.search.includes(q));c.style.display=ok?"":"none";if(ok)count++});if(empty)empty.style.display=count?"none":"block"}filters.forEach(b=>b.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));b.classList.add("active");filterProjects()}));if(search)search.addEventListener("input",filterProjects);
if(location.hash&&location.hash!=="#"){const target=document.querySelector(location.hash);if(target)setTimeout(()=>target.scrollIntoView({behavior:"smooth"}),500)}
})();